name: Full GitHub Actions Workflow

on:
  push:
    branches: [ main ]

env:
  MY_VARIABLE: "This is a variable"

jobs:
  job1-hello-world:
    name: Exo 1 à 4 – Base + Env + Secret + Bash
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Hello GitHub Actions
        run: echo "Hello, GitHub Actions!"

      - name: Show environment variable
        run: echo "Variable: ${{ env.MY_VARIABLE }}"

      - name: Use secret (masqué automatiquement)
        run: echo "Secret: ${{ secrets.MY_SECRET }}"

      - name: Create hello.txt with Bash
        run: echo "Hello world" > hello.txt

      - name: Display content of hello.txt
        run: cat hello.txt

  job2-tests-and-coverage:
    name: Exo 5 à 7 – Tests + Couverture
    runs-on: ubuntu-latest
    needs: job1-hello-world

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  job3-deploy-gh-pages:
    name: Exo 8 – Déploiement GitHub Pages
    runs-on: ubuntu-latest
    needs: job2-tests-and-coverage

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

  job4-linting:
    name: Exo 9 – Linting via Marketplace
    runs-on: ubuntu-latest
    needs: job1-hello-world

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
